#!/bin/bash

# activate venv
. venv/bin/activate

# flask vars
export FLASK_APP=server
export FLASK_ENV=development
export DOTENV='.env'

# install flask dependencies
pip install -e .

# run server
flask run

